# Generated by Django 5.0 on 2026-02-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='signed_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
