# Generated by Django 5.0 on 2026-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemuser_asset_brand_asset_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(default='Usado', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
